#!/usr/bin/env node
/**
 * Precompile Nunjucks templates so they can run on Cloudflare Workers.
 *
 * Workers blocks `new Function()` / eval. Nunjucks compiles templates by
 * generating JS source code and calling `new Function(...)` — which fails on
 * Workers. The fix is precompilation at build time: convert each template to
 * its compiled JS form ahead of time, bundle the result, then use Nunjucks'
 * PrecompiledLoader to execute the precompiled functions without invoking the
 * parser/compiler at runtime.
 *
 * This script reads:
 *   - prompts/recommender.yaml      (extracts system + user template bodies)
 *   - prompts/suggestions.yaml      (extracts system + user template bodies)
 *   - prompts/partials/brand-voice.njk
 *   - prompts/partials/block-guide.njk
 *   - prompts/partials/product-catalog.njk
 *   - prompts/partials/accessories.njk
 *
 * And writes:
 *   - prompts/compiled.js — a JS module exporting a precompiled template map
 *     compatible with nunjucks.PrecompiledLoader.
 *
 * Run via `npm run precompile-prompts` or automatically as a prebuild step.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import nunjucks from 'nunjucks';
import yaml from 'yaml';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const PROMPTS_DIR = path.resolve(HERE, '../prompts');
const OUT_PATH = path.join(PROMPTS_DIR, 'compiled.js');

function read(rel) {
  return readFileSync(path.join(PROMPTS_DIR, rel), 'utf8');
}

// Templates to precompile: name → source text.
// Names match the paths the runtime references via {% include %} or getTemplate().
const TEMPLATES = {
  'partials/brand-voice.njk': read('partials/brand-voice.njk'),
  'partials/block-guide.njk': read('partials/block-guide.njk'),
  'partials/product-catalog.njk': read('partials/product-catalog.njk'),
  'partials/accessories.njk': read('partials/accessories.njk'),
};

// Extract system + user template bodies from the YAML prompt files.
for (const [yamlFile, prefix] of [['recommender.yaml', 'recommender'], ['suggestions.yaml', 'suggestions']]) {
  const parsed = yaml.parse(read(yamlFile));
  if (!parsed?.system || !parsed?.user) {
    throw new Error(`${yamlFile} missing system/user`);
  }
  TEMPLATES[`${prefix}/system`] = parsed.system;
  TEMPLATES[`${prefix}/user`] = parsed.user;
}

// nunjucks.precompileString returns JS source for ONE template.
// Each output starts with:
//   (function() { (window.nunjucksPrecompiled = window.nunjucksPrecompiled || {})["name"] = ... })()
//
// We shim globalThis.nunjucksPrecompiled before the IIFEs run so they populate
// our local object instead of window. Then we export that object.

const parts = [
  '// AUTO-GENERATED by tools/precompile-prompts.js — do not edit.',
  '// Run `npm run precompile-prompts` to regenerate.',
  '',
  '/* eslint-disable */',
  '',
  '// Shim so the precompiled IIFEs (which reference `window.nunjucksPrecompiled`)',
  '// populate a local object we can export.',
  'if (typeof globalThis !== "undefined") {',
  '  globalThis.nunjucksPrecompiled = globalThis.nunjucksPrecompiled || {};',
  '}',
  'if (typeof window === "undefined") {',
  '  // Workers / Node: ensure `window` resolves to globalThis so the IIFEs work.',
  '  // This assignment is module-scoped and does not escape.',
  '  var window = globalThis;',
  '}',
  '',
];

for (const [name, src] of Object.entries(TEMPLATES)) {
  const compiled = nunjucks.precompileString(src, { name });
  parts.push(`// ── ${name} ──`);
  parts.push(compiled);
  parts.push('');
}

parts.push('export default globalThis.nunjucksPrecompiled;');

writeFileSync(OUT_PATH, parts.join('\n'), 'utf8');
console.log(`Wrote ${OUT_PATH} (${Object.keys(TEMPLATES).length} templates)`);
